//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSData.MksServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MksServiceReference.INoAjaxService")]
    public interface INoAjaxService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INoAjaxService/GetEmpSalary", ReplyAction="http://tempuri.org/INoAjaxService/GetEmpSalaryResponse")]
        string GetEmpSalary(string EmpId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INoAjaxService/GetEmpSalary", ReplyAction="http://tempuri.org/INoAjaxService/GetEmpSalaryResponse")]
        System.Threading.Tasks.Task<string> GetEmpSalaryAsync(string EmpId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INoAjaxService/AdjustBalance", ReplyAction="http://tempuri.org/INoAjaxService/AdjustBalanceResponse")]
        string AdjustBalance(string Uid, string Adjustment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INoAjaxService/AdjustBalance", ReplyAction="http://tempuri.org/INoAjaxService/AdjustBalanceResponse")]
        System.Threading.Tasks.Task<string> AdjustBalanceAsync(string Uid, string Adjustment);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface INoAjaxServiceChannel : MSData.MksServiceReference.INoAjaxService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NoAjaxServiceClient : System.ServiceModel.ClientBase<MSData.MksServiceReference.INoAjaxService>, MSData.MksServiceReference.INoAjaxService {
        
        public NoAjaxServiceClient() {
        }
        
        public NoAjaxServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NoAjaxServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NoAjaxServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NoAjaxServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetEmpSalary(string EmpId) {
            return base.Channel.GetEmpSalary(EmpId);
        }
        
        public System.Threading.Tasks.Task<string> GetEmpSalaryAsync(string EmpId) {
            return base.Channel.GetEmpSalaryAsync(EmpId);
        }
        
        public string AdjustBalance(string Uid, string Adjustment) {
            return base.Channel.AdjustBalance(Uid, Adjustment);
        }
        
        public System.Threading.Tasks.Task<string> AdjustBalanceAsync(string Uid, string Adjustment) {
            return base.Channel.AdjustBalanceAsync(Uid, Adjustment);
        }
    }
}
